// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package invoice

import (
	"inventory-service-go/commons"
)

// Injectors from wire.go:

func InitializeInvoiceService() (InvoiceService, error) {
	db := commons.GetDB()
	invoiceRepositoryImpl := NewInvoiceRepository(db)
	invoiceServiceImpl := NewInvoiceService(invoiceRepositoryImpl)
	return invoiceServiceImpl, nil
}
