// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package person

import (
	"inventory-service-go/commons"
)

// Injectors from wire.go:

func InitializePersonService() PersonServiceImpl {
	db := commons.GetDB()
	personRepository := NewPersonRepository(db)
	personServiceImpl := NewPersonService(personRepository)
	return personServiceImpl
}
