POST http://localhost:8080/api/v1/authorize
Content-Type: application/json

{
  "client_id": "foo",
  "client_secret": "bar"
}

> {%
    client.global.set("access_token", response.body.token);
%}

###
OPTIONS http://localhost:8080/api/v1/invoices?page_size=100

###

GET http://localhost:8080/api/v1/invoices?last_id=24&page_size=1
Authorization: Bearer {{access_token}}
###

POST http://localhost:8080/api/v1/invoices
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_id": "2b1b425e-dee2-4227-8d94-f470a0ce0cd0",
  "paid": false,
  "total": 125.0,
  "created_by": "http_client"
}

> {%
 client.global.set("new_invoice_id", response.body.id)
 %}

###
GET http://localhost:8080/api/v1/invoices/{{new_invoice_id}}
Authorization: Bearer {{access_token}}
###
PUT http://localhost:8080/api/v1/invoices/{{new_invoice_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "{{new_invoice_id}}",
  "paid": true,
  "total": 130.5,
  "last_changed_by": "http_client"
}
###
POST http://localhost:8080/api/v1/invoices/{{new_invoice_id}}/items
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "invoice_id": "{{new_invoice_id}}",
  "items": ["6f4bdd88-d12e-421a-bac7-92ed2d9035aa", "2492b388-e0b9-47ca-97a1-8f5ba75441ea"]
}
###
GET http://localhost:8080/api/v1/invoices/{{new_invoice_id}}?withItems=true
Authorization: Bearer {{access_token}}
###
DELETE http://localhost:8080/api/v1/invoices/{{new_invoice_id}}/items/6f4bdd88-d12e-421a-bac7-92ed2d9035aa
Authorization: Bearer {{access_token}}
###
DELETE http://localhost:8080/api/v1/invoices/{{new_invoice_id}}
Authorization: Bearer {{access_token}}
###