// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package item

import (
	"inventory-service-go/commons"
)

// Injectors from wire.go:

func InitializeItemService() (ItemService, error) {
	db := commons.GetDB()
	itemRepositoryImpl := NewItemRepository(db)
	itemServiceImpl := NewItemService(itemRepositoryImpl)
	return itemServiceImpl, nil
}
